#  -------------------------------------------------------------------------------------------------
#   Copyright (c) 2016-2025.  SupportVectors AI Lab
#   This code is part of the training material and, therefore, part of the intellectual property.
#   It may not be reused or shared without the explicit, written permission of SupportVectors.
#
#   Use is limited to the duration and purpose of the training at SupportVectors.
#
#   Author: SupportVectors AI Training Team
#  -------------------------------------------------------------------------------------------------
'''
This module contains the code for training and evaluating the relevance detection model.  In the context of this module,
positive relevance is defined as a sentence that is associated with a label of 1 and negative relevance is defined as a sentence 
that is associated with a label of 0.

The model is trained using the following approach:
    1. Start with the ModernBert-Large model from HuggingFace and set it up for sequence classification.
    2. Use the synthetic data under data/synthetic_data/ generated by the synthetic_data_generation module.  This contains
    positive and negative samples.  
    3. Shuffle the data and use 80% of the data for training and 20% for validation.
    4. Train the model on the training set by fine-tuning the ModernBert-Large model.
    5. Give options to do full-fine-tuning or fine-tuning only the classification head.
    6. The eventual goal is to achieve accuracy, precision and recall of greater than 99% on the validation set.
    7. Identify the appropriate threshold to reach the desired accuracy, precision and recall.
    8. Evaluate the model on the validation set with the identified threshold and report the accuracy, precision and recall.
    9. Save the fine-tuned model.
    10. Use the model to predict the relevance of a given sentence.
'''

import json
import logging
import gc
from typing import Dict, List, Tuple, Optional
from pathlib import Path

import torch
import numpy as np
from transformers import (
    AutoTokenizer, 
    AutoModelForSequenceClassification, 
    Trainer, 
    TrainingArguments,
    EarlyStoppingCallback
)
from datasets import Dataset
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report
from sklearn.model_selection import train_test_split

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def get_device() -> torch.device:
    """
    Automatically detect and return the best available device for PyTorch.
    
    Returns:
        torch.device: The best available device (CUDA, MPS, or CPU)
    """
    if torch.cuda.is_available():
        device = torch.device("cuda")
        logger.info(f"Using CUDA device: {torch.cuda.get_device_name(0)}")
        logger.info(f"CUDA memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
        logger.info("Using MPS device (Apple Silicon)")
    else:
        device = torch.device("cpu")
        logger.info("Using CPU device")
    
    return device


def clear_gpu_memory():
    """Clear GPU memory to prevent memory leaks."""
    if torch.cuda.is_available():
        gc.collect()
        torch.cuda.empty_cache()
        logger.debug("GPU memory cleared")


class DataProcessor:
    """Handles data loading, preprocessing, and splitting for the relevance detection model."""
    
    def __init__(self, data_path: str = "data/synthetic_data/synthetic_data.jsonl", split_ratio: float = 0.2):
        """
        Initialize the data processor.
        
        Args:
            data_path: Path to the JSONL file containing synthetic data
            split_ratio: Ratio of data to split into test set out of total data (default: 0.2)
        """
        self.data_path = Path(data_path)
        self.split_ratio = split_ratio
        self.train_dataset = None
        self.val_dataset = None
        
    def load_data(self) -> Tuple[Dataset, Dataset]:
        """
        Load and split the synthetic data into training and validation sets.
        
        Returns:
            Tuple of (train_dataset, val_dataset)
        """
        if not self.data_path.exists():
            raise FileNotFoundError(f"Data file not found: {self.data_path}")
            
        # Load data from JSONL file
        data = []
        with open(self.data_path, 'r', encoding='utf-8') as f:
            for line in f:
                item = json.loads(line.strip())
                # Filter out any labels that aren't 0 or 1 (binary classification)
                if item['label'] in [0, 1]:
                    data.append(item)
                else:
                    logger.warning(f"Filtering out sample with invalid label {item['label']}: {item['text'][:50]}...")
        
        # Check if we can use stratification
        labels = [item['label'] for item in data]
        label_counts = np.bincount(labels)
        
        # If any class has less than 2 samples, don't use stratification
        if np.min(label_counts) < 2:
            logger.warning(f"Class distribution: {label_counts}. Some classes have < 2 samples. Disabling stratification.")
            train_data, val_data = train_test_split(
                data, shuffle=True, test_size=self.split_ratio, random_state=42
            )
        else:
            train_data, val_data = train_test_split(
                data, shuffle=True, test_size=self.split_ratio, random_state=42, stratify=labels
            )
        
        # Convert to HuggingFace datasets
        self.train_dataset = Dataset.from_list(train_data)
        self.val_dataset = Dataset.from_list(val_data)
        
        # Log class distribution
        train_labels = [item['label'] for item in train_data]
        val_labels = [item['label'] for item in val_data]
        train_dist = np.bincount(train_labels)
        val_dist = np.bincount(val_labels)
        
        logger.info(f"Loaded {len(train_data)} training samples and {len(val_data)} validation samples")
        logger.info(f"Training class distribution: {train_dist.tolist()}")
        logger.info(f"Validation class distribution: {val_dist.tolist()}")
        
        return self.train_dataset, self.val_dataset


class RelevanceDetector:
    """Main class for training and evaluating the relevance detection model."""
    
    def __init__(
        self,
        model_name: str = "answerdotai/ModernBERT-large", 
        max_length: int = 512,
        batch_size: int = 16,
        learning_rate: float = 2e-5,
        num_epochs: int = 3,
        warmup_steps: int = 500,
        weight_decay: float = 0.01,
        output_dir: str = "models/relevance_detector",
        device: Optional[torch.device] = None,
        use_mixed_precision: bool = True,
        gradient_accumulation_steps: int = 1
    ):
        """
        Initialize the relevance detector.
        
        Args:
            model_name: HuggingFace model name
            max_length: Maximum sequence length
            batch_size: Training batch size
            learning_rate: Learning rate for training
            num_epochs: Number of training epochs
            warmup_steps: Number of warmup steps
            weight_decay: Weight decay for regularization
            output_dir: Directory to save the model
            device: PyTorch device to use (auto-detected if None)
            use_mixed_precision: Whether to use mixed precision training
            gradient_accumulation_steps: Number of steps to accumulate gradients
        """
        self.model_name = model_name
        self.max_length = max_length
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.warmup_steps = warmup_steps
        self.weight_decay = weight_decay
        self.output_dir = Path(output_dir)
        self.device = device if device is not None else get_device()
        self.use_mixed_precision = use_mixed_precision and self.device.type != "cpu"
        self.gradient_accumulation_steps = gradient_accumulation_steps
        
        # Initialize components
        self.tokenizer = None
        self.model = None
        self.trainer = None
        self.data_processor = DataProcessor()
        self.optimal_threshold = 0.5
        
        # Create output directory
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Log device and optimization settings
        logger.info(f"Device: {self.device}")
        logger.info(f"Mixed precision: {self.use_mixed_precision}")
        logger.info(f"Gradient accumulation steps: {self.gradient_accumulation_steps}")
        
    def setup_model(self, freeze_backbone: bool = False):
        """
        Set up the tokenizer and model.
        
        Args:
            freeze_backbone: Whether to freeze the backbone and only train the classification head
        """
        logger.info(f"Loading tokenizer and model: {self.model_name}")
        
        # Load tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
            
        # Load model
        self.model = AutoModelForSequenceClassification.from_pretrained(
            self.model_name,
            num_labels=2,  # Binary classification
            problem_type="single_label_classification"
        )
        
        # Move model to device
        self.model = self.model.to(self.device)
        
        # Freeze backbone if requested
        if freeze_backbone:
            for param in self.model.base_model.parameters():
                param.requires_grad = False
            logger.info("Backbone frozen, only classification head will be trained")
        
        # Log model parameters
        total_params = sum(p.numel() for p in self.model.parameters())
        trainable_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)
        logger.info(f"Total parameters: {total_params:,}")
        logger.info(f"Trainable parameters: {trainable_params:,}")
        
        logger.info("Model setup complete")
        
    def tokenize_function(self, examples: Dict) -> Dict:
        """
        Tokenize the input examples.
        
        Args:
            examples: Dictionary containing 'text' and 'label' keys
            
        Returns:
            Tokenized examples with labels preserved
        """
        tokenized = self.tokenizer(
            examples['text'],
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        
        # Add labels to the tokenized output
        tokenized['labels'] = examples['label']
        
        return tokenized
        
    def compute_metrics(self, eval_pred: Tuple) -> Dict:
        """
        Compute evaluation metrics.
        
        Args:
            eval_pred: Tuple of (predictions, labels)
            
        Returns:
            Dictionary of metrics
        """
        predictions, labels = eval_pred
        predictions = np.argmax(predictions, axis=1)
        
        accuracy = accuracy_score(labels, predictions)
        precision, recall, f1, _ = precision_recall_fscore_support(
            labels, predictions, average='binary'
        )
        
        return {
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1': f1
        }
        
    def find_optimal_threshold(self, val_dataset: Dataset) -> float:
        """
        Find the optimal threshold for binary classification.
        
        Args:
            val_dataset: Validation dataset
            
        Returns:
            Optimal threshold value
        """
        logger.info("Finding optimal threshold...")
        
        # Get predictions on validation set
        val_predictions = self.trainer.predict(val_dataset)
        probabilities = torch.softmax(torch.tensor(val_predictions.predictions), dim=1)
        positive_probs = probabilities[:, 1].numpy()
        labels = val_predictions.label_ids
        
        # Try different thresholds
        thresholds = np.arange(0.1, 1.0, 0.05)
        best_f1 = 0
        best_threshold = 0.5
        
        for threshold in thresholds:
            predictions = (positive_probs >= threshold).astype(int)
            _, _, f1, _ = precision_recall_fscore_support(labels, predictions, average='binary')
            
            if f1 > best_f1:
                best_f1 = f1
                best_threshold = threshold
                
        self.optimal_threshold = best_threshold
        logger.info(f"Optimal threshold: {best_threshold:.3f} (F1: {best_f1:.3f})")
        
        return best_threshold
        
    def train(self, freeze_backbone: bool = False) -> Dict:
        """
        Train the relevance detection model.
        
        Args:
            freeze_backbone: Whether to freeze the backbone and only train the classification head
            
        Returns:
            Training results
        """
        logger.info("Starting model training...")
        
        # Clear GPU memory before training
        clear_gpu_memory()
        
        # Load and prepare data
        train_dataset, val_dataset = self.data_processor.load_data()
        
        # Setup model
        self.setup_model(freeze_backbone=freeze_backbone)
        
        # Tokenize datasets
        tokenized_train = train_dataset.map(
            self.tokenize_function, 
            batched=True, 
            remove_columns=['text']  # Only remove text column, keep labels
        )
        tokenized_val = val_dataset.map(
            self.tokenize_function, 
            batched=True, 
            remove_columns=['text']  # Only remove text column, keep labels
        )
        
        # Determine optimal batch size based on device
        effective_batch_size = self.batch_size
        if self.device.type == "cuda":
            # Try to use larger batch size on GPU
            gpu_memory = torch.cuda.get_device_properties(0).total_memory / 1e9
            if gpu_memory >= 8:  # 8GB or more
                effective_batch_size = min(self.batch_size * 2, 32)
            elif gpu_memory >= 4:  # 4GB or more
                effective_batch_size = min(self.batch_size, 16)
            else:
                effective_batch_size = min(self.batch_size // 2, 8)
        elif self.device.type == "mps":
            # MPS typically has less memory than CUDA
            effective_batch_size = min(self.batch_size // 2, 8)
        
        logger.info(f"Using effective batch size: {effective_batch_size}")

        fp16 = False
        bf16 = False
        if self.device.type == "cuda":
            if self.use_mixed_precision:
                if hasattr(torch.cuda, "is_bf16_supported") and torch.cuda.is_bf16_supported():
                    bf16 = True
                else:
                    fp16 = True

        # Setup training arguments
        training_args = TrainingArguments(
            output_dir=str(self.output_dir),
            num_train_epochs=self.num_epochs,
            per_device_train_batch_size=effective_batch_size,
            per_device_eval_batch_size=effective_batch_size,
            learning_rate=self.learning_rate,
            warmup_steps=self.warmup_steps,
            weight_decay=self.weight_decay,
            logging_dir=str(self.output_dir / "logs"),
            logging_steps=100,
            eval_strategy="steps",
            eval_steps=500,
            save_strategy="steps",
            save_steps=500,
            load_best_model_at_end=True,
            metric_for_best_model="f1",
            greater_is_better=True,
            push_to_hub=False,
            report_to=None,  # Disable wandb/tensorboard
            # GPU optimizations
            fp16=fp16,
            bf16=bf16,
            dataloader_pin_memory=self.device.type != "cpu",
            dataloader_num_workers=0 if self.device.type == "mps" else 2,
            gradient_accumulation_steps=self.gradient_accumulation_steps,
            # Memory optimizations
            gradient_checkpointing=True,
            optim="adamw_torch",
            # Additional optimizations
            remove_unused_columns=False,
            ddp_find_unused_parameters=False,
        )
        
        # Initialize trainer
        self.trainer = Trainer(
            model=self.model,
            args=training_args,
            train_dataset=tokenized_train,
            eval_dataset=tokenized_val,
            compute_metrics=self.compute_metrics,
            callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
        )
        
        # Train the model
        train_result = self.trainer.train()
        
        # Find optimal threshold
        self.find_optimal_threshold(tokenized_val)
        
        # Evaluate with optimal threshold
        final_metrics = self.evaluate(tokenized_val)
        
        # Save model and tokenizer
        self.save_model()
        
        # Clear GPU memory after training
        clear_gpu_memory()
        
        logger.info("Training completed successfully!")
        return {
            'train_loss': train_result.training_loss,
            'final_metrics': final_metrics,
            'optimal_threshold': self.optimal_threshold
        }
        
    def evaluate(self, dataset: Dataset) -> Dict:
        """
        Evaluate the model on a dataset.
        
        Args:
            dataset: Dataset to evaluate on
            
        Returns:
            Evaluation metrics
        """
        logger.info("Evaluating model...")
        
        # Get predictions
        predictions = self.trainer.predict(dataset)
        probabilities = torch.softmax(torch.tensor(predictions.predictions), dim=1)
        positive_probs = probabilities[:, 1].numpy()
        labels = predictions.label_ids
        
        # Apply optimal threshold
        thresholded_predictions = (positive_probs >= self.optimal_threshold).astype(int)
        
        # Calculate metrics
        accuracy = accuracy_score(labels, thresholded_predictions)
        precision, recall, f1, _ = precision_recall_fscore_support(
            labels, thresholded_predictions, average='binary'
        )
        
        # Generate detailed classification report
        report = classification_report(
            labels, 
            thresholded_predictions, 
            target_names=['Irrelevant', 'Relevant'],
            output_dict=True
        )
        
        metrics = {
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1': f1,
            'threshold': self.optimal_threshold,
            'detailed_report': report
        }
        
        logger.info("Evaluation Results:")
        logger.info(f"  Accuracy: {accuracy:.4f}")
        logger.info(f"  Precision: {precision:.4f}")
        logger.info(f"  Recall: {recall:.4f}")
        logger.info(f"  F1-Score: {f1:.4f}")
        logger.info(f"  Threshold: {self.optimal_threshold:.3f}")
        
        return metrics
        
    def evaluate_dataset(self, dataset: Dataset, batch_size: int = 32) -> Dict:
        """
        Evaluate the model on a dataset using the same logic as predict_batch.
        
        Args:
            dataset: Dataset to evaluate on
            batch_size: Batch size for processing (default: 32)
            
        Returns:
            Evaluation metrics
        """
        logger.info("Evaluating model using predict_batch logic...")
        
        # Get predictions using the same logic as predict_batch
        if self.model is None or self.tokenizer is None:
            raise ValueError("Model not loaded. Call load_model() or train() first.")
            
        # Tokenize the dataset
        tokenized_val = dataset.map(
            self.tokenize_function, 
            batched=True, 
            remove_columns=['text']  # Only remove text column, keep labels
        )
        
        # Process in batches to avoid memory issues and improve speed
        all_predictions = []
        all_labels = []
        
        # Set model to evaluation mode
        self.model.eval()
        
        # Process dataset in batches
        for i in range(0, len(tokenized_val), batch_size):
            batch_end = min(i + batch_size, len(tokenized_val))
            batch_data = tokenized_val.select(range(i, batch_end))
            
            # Extract batch data and move to device
            input_ids = torch.tensor(batch_data['input_ids']).to(self.device)
            attention_mask = torch.tensor(batch_data['attention_mask']).to(self.device)
            batch_labels = batch_data['labels']
            
            # Get predictions for this batch
            with torch.no_grad():
                outputs = self.model(input_ids=input_ids, attention_mask=attention_mask)
                probabilities = torch.softmax(outputs.logits, dim=1)
                positive_probs = probabilities[:, 1].cpu().numpy()
            
            all_predictions.extend(positive_probs)
            all_labels.extend(batch_labels)
            
            # Log progress for large datasets
            if len(tokenized_val) > 1000 and (i // batch_size) % 10 == 0:
                logger.info(f"Processed {batch_end}/{len(tokenized_val)} samples...")
        
        # Convert to numpy arrays
        all_predictions = np.array(all_predictions)
        all_labels = np.array(all_labels)
        
        # Apply optimal threshold
        thresholded_predictions = (all_predictions >= self.optimal_threshold).astype(int)
        
        # Calculate metrics
        accuracy = accuracy_score(all_labels, thresholded_predictions)
        precision, recall, f1, _ = precision_recall_fscore_support(
            all_labels, thresholded_predictions, average='binary'
        )
        
        # Generate detailed classification report
        report = classification_report(
            all_labels, 
            thresholded_predictions, 
            target_names=['Irrelevant', 'Relevant'],
            output_dict=True
        )
        
        metrics = {
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1': f1,
            'threshold': self.optimal_threshold,
            'detailed_report': report
        }
        
        logger.info("Evaluation Results (using predict_batch logic):")
        logger.info(f"  Accuracy: {accuracy:.4f}")
        logger.info(f"  Precision: {precision:.4f}")
        logger.info(f"  Recall: {recall:.4f}")
        logger.info(f"  F1-Score: {f1:.4f}")
        logger.info(f"  Threshold: {self.optimal_threshold:.3f}")
        
        return metrics
        
    def save_model(self):
        """Save the trained model and tokenizer."""
        logger.info(f"Saving model to {self.output_dir}")
        
        # Save model and tokenizer
        self.trainer.save_model(str(self.output_dir))
        self.tokenizer.save_pretrained(str(self.output_dir))
        
        # Save threshold
        threshold_file = self.output_dir / "threshold.json"
        with open(threshold_file, 'w') as f:
            json.dump({'threshold': self.optimal_threshold}, f)
            
        logger.info("Model saved successfully")
        
    def load_model(self, model_path: str):
        """
        Load a trained model.
        
        Args:
            model_path: Path to the saved model
        """
        model_path = Path(model_path)
        
        logger.info(f"Loading model from {model_path}")
        
        # Load tokenizer and model
        self.tokenizer = AutoTokenizer.from_pretrained(str(model_path))
        self.model = AutoModelForSequenceClassification.from_pretrained(str(model_path))
        
        # Move model to device
        self.model = self.model.to(self.device)
        
        # Load threshold
        threshold_file = model_path / "threshold.json"
        if threshold_file.exists():
            with open(threshold_file, 'r') as f:
                threshold_data = json.load(f)
                self.optimal_threshold = threshold_data['threshold']
        
        logger.info("Model loaded successfully")
        
    def predict(self, text: str) -> Dict:
        """
        Predict the relevance of a given text.
        
        Args:
            text: Input text to classify
            
        Returns:
            Dictionary containing prediction results
        """
        if self.model is None or self.tokenizer is None:
            raise ValueError("Model not loaded. Call load_model() or train() first.")
            
        # Tokenize input
        inputs = self.tokenizer(
            text,
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        
        # Move inputs to device
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        # Get prediction
        with torch.no_grad():
            outputs = self.model(**inputs)
            probabilities = torch.softmax(outputs.logits, dim=1)
            positive_prob = probabilities[0, 1].cpu().item()
            
        # Apply threshold
        is_relevant = positive_prob >= self.optimal_threshold
        
        return {
            'text': text,
            'relevance_probability': positive_prob,
            'is_relevant': is_relevant,
            'threshold': self.optimal_threshold,
            'confidence': max(positive_prob, 1 - positive_prob)
        }
        
    def predict_batch(self, texts: List[str]) -> List[Dict]:
        """
        Predict relevance for a batch of texts.
        
        Args:
            texts: List of input texts
            
        Returns:
            List of prediction results
        """
        if self.model is None or self.tokenizer is None:
            raise ValueError("Model not loaded. Call load_model() or train() first.")
            
        # Tokenize inputs
        inputs = self.tokenizer(
            texts,
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        
        # Move inputs to device
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        # Get predictions
        with torch.no_grad():
            outputs = self.model(**inputs)
            probabilities = torch.softmax(outputs.logits, dim=1)
            positive_probs = probabilities[:, 1].cpu().numpy()
            
        # Apply threshold and format results
        results = []
        for i, (text, prob) in enumerate(zip(texts, positive_probs)):
            is_relevant = prob >= self.optimal_threshold
            results.append({
                'text': text,
                'relevance_probability': prob,
                'is_relevant': is_relevant,
                'threshold': self.optimal_threshold,
                'confidence': max(prob, 1 - prob)
            })
            
        return results


def main():
    """Main function to demonstrate the relevance detector usage."""
    model_path = "models/relevance_detector"
    
    # Clear GPU memory at start
    clear_gpu_memory()
    
    # Initialize the detector with GPU optimizations
    detector = RelevanceDetector(
        model_name="answerdotai/ModernBERT-large",
        batch_size=8,
        learning_rate=2e-5,
        num_epochs=3,
        output_dir=model_path,
        use_mixed_precision=True,
        gradient_accumulation_steps=2
    )
    
    # Train the model
    results = detector.train(freeze_backbone=False)
    print("Training Results:", results)

    # Model is saved by the train() method
    logger.info(f"Model saved to {model_path}")

    # Load the trained model for evaluation
    detector.load_model(model_path)
        
    # Test predictions
    test_texts = [
        "Dolphins have been observed teaching each other complex hunting techniques.",
        "The new smartphone app allows users to track their daily steps.",
        "Elephants have a highly developed brain and are considered one of the smartest animals.",
        "The economy is expected to experience a significant downturn."
    ]
    
    print("\nTesting predictions:")
    for text in test_texts:
        result = detector.predict(text)
        print(f"Text: {text[:50]}...")
        print(f"  Relevant: {result['is_relevant']} (prob: {result['relevance_probability']:.3f})")
        print()
    
    # Clear GPU memory at end
    clear_gpu_memory()


if __name__ == "__main__":
    main()