[project]
name = "response-grounding"
version = "0.1.0"
description = "response_grounding"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "en-core-web-sm",
    "sentence-transformers>=3.0.0",
    "svlearn-bootcamp>=0.1.7",
    "sv-rag-pipeline",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]

# If you also build sdists and want data included:
[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
    # ... other includes like README, pyproject.toml, etc.
]

[tool.hatch.build.targets.wheel]
packages = ["src/response_grounding"]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
sv-rag-pipeline = { path = "../../llm_bootcamp_curriculum/sv_rag_pipeline", editable = true }
